### ISSUE TITLE
Invalid where operator: !=

### ISSUE THREAD

**Issue by thinhnd8752** [Adldap2/Adldap2#441] opened 2017-09-25 18:30 UTC
- Adldap2 Version: ^8.0
- LDAP Type: Active Directory
- PHP Version: 7.0

### Description:
It appears Query builer can not parse **!=** operator.
PHP Fatal error:  Uncaught InvalidArgumentException: Invalid where operator: !=.
### Steps To Reproduce:
```
$enabled_users_filter = [
                                ['objectCategory','=','person'],
                                ['objectClass','=','user'],
                                ['ou','!=','Some OU'],
                        ];
                $result = $provider->search()->where($enabled_users_filter)->sortBy('cn','asc')->paginate(10000)->getResults();
```
Please let me know if you need more details.
Thanks and nice day for all of you.

**Comment by stevebauman** [comment] 2017-09-25 20:10
Hi @thinhnd8752,

This is actually a documentation issue. The `not equal` operator should be only an exclamation mark (`!`), no equals.

This was originally to fall in line with how LDAP filters are actually constructed, for example: 

```
(!(samaccountname=jdoe))
```

I'm going to be adding an alias so both work. This is to align with PHP and MySQL with their *not equal* operators.

I'll close this issue once implemented, however this is not a bug.

**Comment by stevebauman** [comment] 2017-09-25 21:22
https://github.com/Adldap2/Adldap2/commit/28498734a28b934b5b6b6b3c00fbc8a337aa27ac

**Closed by stevebauman** 2017-09-25 21:22 UTC
Labels: implenting, not an issue
