### ISSUE TITLE
Getting users from OpenLDAP gives an empty array

### ISSUE THREAD

**Issue by avinash403** [Adldap2/Adldap2#611] opened 2018-11-18 06:24 UTC
- Adldap2 Version: 9.1
- LDAP Type:  OpenLDAP
- PHP Version: 7.1.8

### Description:
I am trying to get users from OpenLDAP server. When I do this 
```
$provider->search()->get()
```
I get all the users + additional data. But when I do 
```
$provider->search()->users()->get()
```
I get an empty array.

My LDAP structure:
![screen shot 2018-11-18 at 11 53 07 am](https://user-images.githubusercontent.com/31030044/48669340-9a9d0100-eb28-11e8-8406-d5f180b4da53.png)

**Comment by stevebauman** [comment] 2018-11-19 22:17
Hi @avinash403,

Did you insert the OpenLDAP schema into your configuration array? For example:

```php
$ad = new Adldap\Adldap();

$config = [
    'schema' => \Adldap\Schemas\OpenLDAP::class,

    // etc...
];

$provider = $ad->addProvider($config);

$provider->connect();
```

https://adldap2.github.io/Adldap2/#/setup?id=using-other-ldap-servers-openldap-freeipa-etc

**Comment by avinash403** [comment] 2018-11-20 01:31
Yes I did

**Comment by stevebauman** [comment] 2018-11-20 01:42
Ok thanks, other users reported this issue using OpenLDAP as well. Patch will be out tonight!

**Comment by avinash403** [comment] 2018-11-20 01:45
Thanks.
This however did work when I used setSchema method directly

**Comment by stevebauman** [comment] 2018-11-20 02:47
Really? That's strange... By calling `$provider->setSchema()`?

**Comment by avinash403** [comment] 2018-12-04 04:55
Sorry my bad. It worked in an older version of this package.
Any update on this ?

**Comment by stevebauman** [comment] 2019-01-09 18:46
Can you call `$provider->search()->get()` and dump the first users attributes and post them here (with sensitive details omitted)?

I'm mainly looking for what the `objectclass` is of each user you've shown, as I've seen some users that posted issues here that use OpenLDAP and the objectclasses of their LDAP users are different from the standard schema.

This would cause the scope to not return the proper results since a non-matching `objectclass` is being added to the search filter.

**Comment by JC5** [comment] 2019-02-16 15:18
OK so that guy never replied but I seem to have a similar issue on the [Forumsys LDAP thing](http://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/).

This is the result of `$users = Adldap::search()->where('uid','pasteur')->get();`

```
Illuminate\Support\Collection Object
(
    [items:protected] => Array
        (
            [0] => Adldap\Models\User Object
                (
                    [exists] => 1
                    [query:protected] => Adldap\Query\Builder Object
                        (
                            [columns] => Array
                                (
                                    [0] => *
                                )

                            [filters] => Array
                                (
                                    [and] => Array
                                        (
                                        )

                                    [or] => Array
                                        (
                                        )

                                    [raw] => Array
                                        (
                                        )

                                )

                            [limit] => 0
                            [paginated] => 
                            [sortByField:protected] => 
                            [sortByDirection:protected] => 
                            [sortByFlags:protected] => 
                            [dn:protected] => dc=example,dc=com
                            [type:protected] => search
                            [raw:protected] => 
                            [nested:protected] => 
                            [connection:protected] => Adldap\Connections\Ldap Object
                                (
                                    [connection:protected] => Resource id #9
                                    [bound:protected] => 1
                                    [useSSL:protected] => 
                                    [useTLS:protected] => 
                                )

                            [grammar:protected] => Adldap\Query\Grammar Object
                                (
                                )

                            [schema:protected] => Adldap\Schemas\ActiveDirectory Object
                                (
                                )

                        )

                    [schema:protected] => Adldap\Schemas\ActiveDirectory Object
                        (
                        )

                    [modifications:protected] => Array
                        (
                        )

                    [dateFormat] => Y-m-d H:i:s
                    [timestampFormat:protected] => YmdHis.0Z
                    [attributes:protected] => Array
                        (
                            [objectclass] => Array
                                (
                                    [0] => inetOrgPerson
                                    [1] => organizationalPerson
                                    [2] => person
                                    [3] => top
                                )

                            [0] => objectclass
                            [sn] => Array
                                (
                                    [0] => Pasteur
                                )

                            [1] => sn
                            [cn] => Array
                                (
                                    [0] => Louis Pasteur
                                )

                            [2] => cn
                            [uid] => Array
                                (
                                    [0] => pasteur
                                )

                            [3] => uid
                            [telephonenumber] => Array
                                (
                                    [0] => 602-214-4978
                                )

                            [4] => telephonenumber
                            [mail] => Array
                                (
                                    [0] => pasteur@ldap.forumsys.com
                                )

                            [5] => mail
                            [distinguishedname] => Array
                                (
                                    [0] => uid=pasteur,dc=example,dc=com
                                )

                        )

                    [original:protected] => Array
                        (
                            [objectclass] => Array
                                (
                                    [0] => inetOrgPerson
                                    [1] => organizationalPerson
                                    [2] => person
                                    [3] => top
                                )

                            [0] => objectclass
                            [sn] => Array
                                (
                                    [0] => Pasteur
                                )

                            [1] => sn
                            [cn] => Array
                                (
                                    [0] => Louis Pasteur
                                )

                            [2] => cn
                            [uid] => Array
                                (
                                    [0] => pasteur
                                )

                            [3] => uid
                            [telephonenumber] => Array
                                (
                                    [0] => 602-214-4978
                                )

                            [4] => telephonenumber
                            [mail] => Array
                                (
                                    [0] => pasteur@ldap.forumsys.com
                                )

                            [5] => mail
                            [distinguishedname] => Array
                                (
                                    [0] => uid=pasteur,dc=example,dc=com
                                )

                        )

                )

        )

)
```
But it doesn't work when I do `Adldap::search()->users()->get();` (adding users()).

Config is as follows.

```
Array
(
    [connections] => Array
        (
            [default] => Array
                (
                    [auto_connect] => 1
                    [connection] => Adldap\Connections\Ldap
                    [schema] => Adldap\Schemas\OpenLDAP
                    [settings] => Array
                        (
                            [account_prefix] => uid=
                            [account_suffix] => ,dc=example,dc=com
                            [hosts] => Array
                                (
                                    [0] => ldap.forumsys.com
                                )

                            [port] => 389
                            [timeout] => 5
                            [base_dn] => dc=example,dc=com
                            [username] => cn=read-only-admin,dc=example,dc=com
                            [password] => password
                            [follow_referrals] => 
                            [use_ssl] => 
                            [use_tls] => 
                        )

                )

        )

)
```

Not really sure what to try next. Any suggestions?

**Comment by JC5** [comment] 2019-02-16 17:52
It works when I set the schema explicitly:

```php
/** @var Adldap\Connections\Provider $provider */
Adldap::getProvider('default')->setSchema(new Adldap\Schemas\OpenLDAP);
echo '<pre>';
print_r(Adldap::search()->users()->get());
```

It might have to do with the laravel package somehow.

**Comment by stevebauman** [comment] 2019-02-16 21:07
Hi @JC5,

Do you have the Laravel package installed? You'll have to publish the configuration files and set the `schema` option in that published file, otherwise the default `ActiveDirectory` schema will be used.

**Comment by JC5** [comment] 2019-02-16 21:21
I did all of that, your package is part of [Firefly III](https://github.com/firefly-iii/firefly-iii). But it seems I can't reproduce the issue. Although this is still weird. My config is as follows:

```
Array
(
    [connections] => Array
        (
            [default] => Array
                (
                    [auto_connect] => 1
                    [connection] => Adldap\Connections\Ldap
                    [schema] => Adldap\Schemas\OpenLDAP
                    [settings] => Array
                        (
                            [account_prefix] => uid=
                            [account_suffix] => ,dc=example,dc=com
                            [hosts] => Array
                                (
                                    [0] => ldap.forumsys.com
                                )

                            [port] => 389
                            [timeout] => 5
                            [base_dn] => dc=example,dc=com
                            [username] => cn=read-only-admin,dc=example,dc=com
                            [password] => password
                            [follow_referrals] => 
                            [use_ssl] => 
                            [use_tls] => 
                        )

                )

        )

)
```

Yet a dump of the default provider using `var_dump(Adldap::getProvider('default'));` always results in the following.

```
/sites/FF3/firefly-iii/app/Http/Controllers/Auth/LoginController.php:86:
object(Adldap\Connections\Provider)[909]
  protected 'connection' => 
    object(Adldap\Connections\Ldap)[912]
      protected 'connection' => resource(10, ldap link)
      protected 'bound' => boolean true
      protected 'useSSL' => boolean false
      protected 'useTLS' => boolean false
  protected 'configuration' => 
    object(Adldap\Configuration\DomainConfiguration)[917]
      protected 'options' => 
        array (size=14)
          'hosts' => 
            array (size=1)
              ...
          'timeout' => string '5' (length=1)
          'version' => int 3
          'port' => string '389' (length=3)
          'schema' => string 'Adldap\Schemas\ActiveDirectory' (length=30)
          'base_dn' => string 'dc=example,dc=com' (length=17)
          'username' => string 'cn=read-only-admin,dc=example,dc=com' (length=36)
          'password' => string 'password' (length=8)
          'account_prefix' => string 'uid=' (length=4)
          'account_suffix' => string ',dc=example,dc=com' (length=18)
          'use_ssl' => boolean false
          'use_tls' => boolean false
          'follow_referrals' => boolean false
          'custom_options' => 
            array (size=0)
              ...
  protected 'schema' => 
    object(Adldap\Schemas\ActiveDirectory)[920]
  protected 'guard' => 
    object(Adldap\Auth\Guard)[921]
      protected 'connection' => 
        object(Adldap\Connections\Ldap)[912]
          protected 'connection' => resource(10, ldap link)
          protected 'bound' => boolean true
          protected 'useSSL' => boolean false
          protected 'useTLS' => boolean false
      protected 'configuration' => 
        object(Adldap\Configuration\DomainConfiguration)[917]
          protected 'options' => 
            array (size=14)
              ...
```

Notice how it says ActiveDirectory?

**Comment by stevebauman** [comment] 2019-02-16 21:23
@JC5 Weird... Is your configuration being cached? Can you run a `php artisan config:clear` to make sure?

**Comment by JC5** [comment] 2019-02-16 21:27
Oh good one, hadn't thought of that 🤐 . But no, the results are the same. It doesn't even protest when I add a completely different class to the config:

```
Array
(
    [connections] => Array
        (
            [default] => Array
                (
                    [auto_connect] => 1
                    [connection] => Adldap\Connections\Ldap
                    [schema] => FireflyIII\Models\TransactionCurrency
                    [settings] => Array
                        (
                            [account_prefix] => uid=
                            [account_suffix] => ,dc=example,dc=com
                            [hosts] => Array
                                (
                                    [0] => ldap.forumsys.com
                                )

                            [port] => 389
                            [timeout] => 5
                            [base_dn] => dc=example,dc=com
                            [username] => cn=read-only-admin,dc=example,dc=com
                            [password] => password
                            [follow_referrals] => 
                            [use_ssl] => 
                            [use_tls] => 
                        )

                )

        )

)
```

Gives no error whatsoever.

**Comment by stevebauman** [comment] 2019-02-17 18:14
Are you sure your config isn't being overridden from your `ldap.php` config file here?

```php
/*
 * Get schema from .env file.
 */
$schema = OpenLDAP::class;

if ('FreeIPA' === envNonEmpty('ADLDAP_CONNECTION_SCHEME', 'OpenLDAP')) {
    $schema = FreeIPA::class;
}
if ('ActiveDirectory' === envNonEmpty('ADLDAP_CONNECTION_SCHEME', 'OpenLDAP')) {
    $schema = ActiveDirectory::class;
}
```
https://github.com/firefly-iii/firefly-iii/blob/fdf147d9c61c0a972387ab630df4a23aeb2fc04e/config/ldap.php#L29-L39

**Comment by JC5** [comment] 2019-02-17 18:20
I am not sure, but I can't pursue the matter for a few days so it's hard to tell. It was tricky to replicate anyway. I'll try it again. But unless the guy from the issue responds, feel free to close this one.

**Closed** 2019-03-22 22:37 UTC
Labels: OpenLDAP, question
